// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-IcIWz_j_3as-uTyI7USLMoa55et0sW8',
    appId: '1:584746387874:web:bdd949d419ae65b51c4afb',
    messagingSenderId: '584746387874',
    projectId: 'workout-logger-dveneris',
    authDomain: 'workout-logger-dveneris.firebaseapp.com',
    storageBucket: 'workout-logger-dveneris.appspot.com',
    measurementId: 'G-37Z8W3HNWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqom1ETja4qOlWtcymuZd_qaJQj-uoNWo',
    appId: '1:584746387874:android:482dade4eed21ef01c4afb',
    messagingSenderId: '584746387874',
    projectId: 'workout-logger-dveneris',
    storageBucket: 'workout-logger-dveneris.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAWDINZs6YZ-CbP95m-8s-1F-mNS1FTyo4',
    appId: '1:584746387874:ios:f3e687e15410f4ef1c4afb',
    messagingSenderId: '584746387874',
    projectId: 'workout-logger-dveneris',
    storageBucket: 'workout-logger-dveneris.appspot.com',
    androidClientId: '584746387874-q9kc5a47kbku8dt9qgfvf6edeiolbhba.apps.googleusercontent.com',
    iosClientId: '584746387874-5752o29jchmlsv8fkokjbgbpq2tvk6k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingTracker',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAWDINZs6YZ-CbP95m-8s-1F-mNS1FTyo4',
    appId: '1:584746387874:ios:f3e687e15410f4ef1c4afb',
    messagingSenderId: '584746387874',
    projectId: 'workout-logger-dveneris',
    storageBucket: 'workout-logger-dveneris.appspot.com',
    androidClientId: '584746387874-q9kc5a47kbku8dt9qgfvf6edeiolbhba.apps.googleusercontent.com',
    iosClientId: '584746387874-5752o29jchmlsv8fkokjbgbpq2tvk6k9.apps.googleusercontent.com',
    iosBundleId: 'com.example.trainingTracker',
  );
}
